added streams
EgorGusenkov/garage pull request #2
Opened 2021-08-08 15:07 UTC by EgorGusenkov

2021-08-11 10:42 UTC, akalinkina-school requested changes

2021-08-11 10:42 UTC, akalinkina-school commented on src/main/java/ru/sberbank/javaschool/garage/Garage.java
> +    Set<Car> garage = new HashSet<>();
в задании - хранить автомобили в упорядоченном виде

2021-08-11 10:42 UTC, akalinkina-school commented on src/main/java/ru/sberbank/javaschool/garage/Garage.java
> +        ofNullable(vin).map(Car::new).filter(garage::add)
1. с момента filter повторяющийся код с предыдущим методом. 
2. Что произойдет, если вызвать метод heshset.add с уже имеющимся авто по вину?

2021-08-11 10:42 UTC, akalinkina-school commented on src/main/java/ru/sberbank/javaschool/garage/Garage.java
>          final StringBuilder sb = new StringBuilder("Garage{");
посмотри StringJoiner

2021-08-11 12:44 UTC, EgorGusenkov commented on src/main/java/ru/sberbank/javaschool/garage/Garage.java
> +        ofNullable(vin).map(Car::new).filter(garage::add)
1. поправим
2. метод add вернет false, т.к. car.hashcode() возвращает hash(vin).

2021-08-12 08:24 UTC, akalinkina-school requested changes

2021-08-12 08:24 UTC, akalinkina-school commented on src/main/java/ru/sberbank/javaschool/garage/Garage.java
> +        ofNullable(vin).map(Car::new).filter(garage::add)
т.е. все будет хорошо, даже если с таким вин уже есть. а нам не нужно заменять машину

2021-08-12 08:55 UTC, EgorGusenkov commented on src/main/java/ru/sberbank/javaschool/garage/Garage.java
> +        ofNullable(vin).map(Car::new).filter(garage::add)
Метод addCar вернет IllegalArgumentException, т.е. мы не сможем добавить автомобиль с таким же вин, нужно только Set сделать private final, или можно ограничить это на уровне Set-а?

2021-08-14 08:31 UTC, akalinkina-school requested changes

2021-08-14 08:31 UTC, akalinkina-school commented on src/main/java/ru/sberbank/javaschool/garage/Garage.java
> +        final StringJoiner stringJoiner = new StringJoiner(":", "{", "}");
можно в одну строчку схлопнуть. Читабельность не пострадает

2021-08-14 08:31 UTC, akalinkina-school commented on src/main/java/ru/sberbank/javaschool/person/model/Person.java
> +    public String getFullName() {
лучше конкатинация .concat

2021-08-14 08:31 UTC, akalinkina-school commented on src/main/java/ru/sberbank/javaschool/transport/model/Car.java
> +        this.owner = null;
по умолчанию и так будет null

2021-08-15 22:11 UTC, akalinkina-school approved these changes

2021-08-17 19:13 UTC, merged